config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboard#index'

  resources :dashboard, only: [:index, :show] do
    resources :expenses, only: [:new, :create, :edit, :destroy]
    resources :incomes, only: [:new, :create, :edit, :destroy] 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '食材' },
    { id: 3, name: '外食' },
    { id: 4, name: 'カフェ' },
    { id: 5, name: 'おやつ' },
    { id: 6, name: '美容費' },
    { id: 7, name: '交通費' },
    { id: 8, name: '日用品' },
    { id: 9, name: '書籍代' },
    { id: 10, name: '特別支出' },
    { id: 11, name: '家賃' },
    { id: 12, name: '電気' },
    { id: 13, name: 'ガス' },
    { id: 14, name: '水道' },
    { id: 15, name: '携帯' },
    { id: 16, name: '通信費' },
    { id: 17, name: '定期' },
    { id: 18, name: '保険' },
    { id: 19, name: 'その他' }
  ]
end

app/models/expense.rb
class Expense < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  validates :ex_amount,    presence: true
  validates :category_id,  presence: true
  validates :about_ex, presence: true

  with_options numericality: { other_than: 1 } do
    validates :category_id
  end

  belongs_to :user
end

app/models/income.rb
class Income < ApplicationRecord
  validates :in_amount,   presence: true
  validates :about_in,    presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
  has_many :incomes
  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @user = current_user.id
  end

  def show
    search_date = params[:id]
    @expenses = current_user.expenses.where(month: search_date.in_time_zone.all_month)
    @incomes = current_user.incomes.where(month: search_date.in_time_zone.all_month)
    @sumexpenses = @expenses.group(:category_id).sum(:ex_amount)
    @categories = Category.find(@sumexpenses.keys)
    @sumincomes = @incomes.sum(:in_amount)
    @total_ex = @expenses.sum(:ex_amount)
    @valiable = @expenses.where(category_id: [2, 3, 4, 5, 6, 7, 8, 9, 10, 19]).sum(:ex_amount)
    @fixed = @expenses.where(category_id: [11, 12, 13, 14, 15, 16, 17, 18]).sum(:ex_amount)
    @diff = @sumincomes - @total_ex
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      redirect_to dashboard_path(expense_params[:month])
    else
      render :new
    end
  end

  def destroy
    expense = Expense.find(expense_params[:id])
    expense.destroy
  end

  def edit
  end

  private

  def expense_params
    params.require(:expense).permit(:ex_amount, :about_ex, :category_id, :month).merge(user_id: current_user.id)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def new
    @income = Income.new
  end

  def create
    @income = Income.new(income_params)
    if @income.save
      redirect_to dashboard_path(income_params[:month])
    else
      render :new
    end
  end

  def destroy
    income = Income.find(income_params[:id])
    income.destroy
  end

  def edit
  end

  private

  def income_params
    params.require(:income).permit(:in_amount, :about_in, :month).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @expense = current_user.expenses
    @income = current_user.incomes
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <div class="side-bar-header">
      <div class="big-month">

      <%= Date.current.strftime('%m')%>
      </div>
      <%= Date.current.strftime('%Y.%m.%d')%>
    </div>
  </div>
  <div class="data-box">
    <div class="btn-center">
      <div class="btn-padding">
        <%= link_to image_tag("income-in.svg", :width => '200', class:"収入の記入"), new_dashboard_income_path(Date.current.strftime('%Y-%m-%d')) %>
      </div>
      <div class="btn-padding">
        <%= link_to image_tag("expense-in.svg", :width => '200', class:"支出の記入"), new_dashboard_expense_path(Date.current.strftime('%Y-%m-%d')) %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <div class="side-bar-header">
      <div class="big-month">
        <%= Date.current.strftime('%m')%>
      </div>
      <%= Date.current.strftime('%Y.%m.%d')%>
    </div>
  </div>
  <div class="data-box">
    <% if user_signed_in? %>
      <div class="data-header">
        <div class="data-header-l"><%= image_tag "icon-income.svg", :width => '150', class:"収入" %></div>
        <div class="data-header-c">
          <table>
            <% @incomes.each do |income| %>
              <tr>
                <td class="td-left"><%= income.about_in %></td>
                <td class="td-right2 amount_sum"><%= income.in_amount.to_s(:delimited) %>
                </td>
              </tr>
            <% end %>
          </table>
          </div>
          <div class="data-header-r">
            <div class="data-header-r-1"></div>
          <table>
            <tr>
              <td class="total-text-bold">収入の合計</td>
            </tr>
            <tr>
              <td class="td-right-total big_sum"> ¥ <%= @sumincomes.to_s(:delimited) %></td>
            </tr>
          </table>
        </div>
      </div>
    <div class="data-footer">
      <div class="data-left">
        <div class="data-left-1">
          <div class="data-left-1-l">
          <%= image_tag "icon-valiable.svg", :width => '172', class:"変動費" %>
          </div>
          <div class="data-left-1-r"></div>
        </div>
        <div class="data-left-2">
          <div class="data-left-2-l"></div>
            <div class="data-left-2-r">
            <table>
              <tr>
                <td class="td-left">食材費</td>
                <td class="td-right amount_sum"><%= @sumexpenses[2] %></td>
              </tr>
              <tr>
                <td class="td-left">外食</td>
                <td class="td-right amount_sum"><%= @sumexpenses[3] %></td>
              </tr>
              <tr>
                <td class="td-left">カフェ</td>
                <td class="td-right amount_sum"><%= @sumexpenses[4] %></td>
              </tr>
              <tr>
                <td class="td-left">おやつ</td>
                <td class="td-right amount_sum"><%= @sumexpenses[5] %></td>
              </tr>
              <tr>
                <td class="td-left">美容費</td>
                <td class="td-right amount_sum"><%= @sumexpenses[6] %></td>
              </tr>
              <tr>
                <td class="td-left">交通費</td>
                <td class="td-right amount_sum"><%= @sumexpenses[7] %></td>
              </tr>
              <tr>
                <td class="td-left">日用品</td>
                <td class="td-righ amount_sum"><%= @sumexpenses[8] %></td>
              </tr>
              <tr>
                <td class="td-left">書籍代</td>
                <td class="td-right amount_sum"><%= @sumexpenses[9] %></td>
              </tr>
              <tr>
                <td class="td-left">特別支出</td>
                <td class="td-right amount_sum"><%= @sumexpenses[10] %></td>
              </tr>
              <tr>
                <td class="td-left">その他</td>
                <td class="td-right amount_sum"><%= @sumexpenses[19] %></td>
              </tr>
              </div>
            </table>
            <div class="total-right2">
              <div class="total-text-bold">変動費の合計</div>
            <div class="td-right-total big_sum pink-font"> ¥ <%= @valiable.to_s(:delimited) %></div>
            </div>
          </div>
        </div>
      </div>
    <div class="data-right">
      <div class= "data-right-1">
      <%= image_tag "icon-fixed.svg", :width => '125', class:"収入" %>
      </div>
      <div class= "data-right-2">
        <table>
              <tr>
                <td class="td-left">家賃</td>
                <td class="td-right amount_sum"><%= @sumexpenses[11] %></td>
              </tr>
              <tr>
                <td class="td-left">電気</td>
                <td class="td-right amount_sum"><%= @sumexpenses[12] %></td>
              </tr>
              <tr>
                <td class="td-left">ガス</td>
                <td class="td-right amount_sum"><%= @sumexpenses[13] %></td>
              </tr>
              <tr>
                <td class="td-left">水道</td>
                <td class="td-right amount_sum"><%= @sumexpenses[14] %></td>
              </tr>
              <tr>
                <td class="td-left">携帯</td>
                <td class="td-right amount_sum"><%= @sumexpenses[15] %></td>
              </tr>
              <tr>
                <td class="td-left">通信費</td>
                <td class="td-right amount_sum"><%= @sumexpenses[16] %></td>
              </tr>
              <tr>
                <td class="td-left">定期</td>
                <td class="td-right amount_sum"><%= @sumexpenses[17] %></td>
              </tr>
              <tr>
                <td class="td-left">保険</td>
                <td class="td-right amount_sum"><%= @sumexpenses[18] %></td>
              </tr>
        </table>
        <div class="total-right2"><br><br>
          <div class="total-text-bold">固定費の合計</div>
          <div class="td-right-total big_sum pink-font"> ¥ <%= @fixed.to_s(:delimited) %></div>
        </div> 
      </div>
      </div> 
      <div class="total">
        <div class= "data-total-l">
          <div class="total-right">
            <div class="total-text-bold"><%= image_tag "income.svg", :width => '45'%> 収入の合計</div>
            <div class="td-right-total big_sum"> ¥ <%= @sumincomes.to_s(:delimited) %></div>
          </div>
        <div class= "data-total-c">
            <div class="total-text-bold"><%= image_tag "expense.svg", :width => '45'%> 支出の合計</div>
            <div class="td-right-total big_sum pink-font"> ¥ <%= @total_ex.to_s(:delimited) %></div>
        </div>
        <div class= "data-total-r">
            <div class="total-text-bold">今月の残り</div>
            <div class="td-right-total big_sum2"> ¥ <%= @diff.to_s(:delimited) %></div>
        </div></div>

        </div>
        </div>
      </div>
    </div>
  </div>
</div>
  <% else %>
  <div class="btn-center">
    <ul>
      <li><div class="btn-data"><%= link_to "家計簿作成", new_dashboard_income_path(Date.current.strftime('%Y-%m-%d')) %></div></li>     
      <li><div class="btn"><%= link_to "支出の入力", new_dashboard_expense_path(Date.current.strftime('%Y-%m-%d')) %></div></li>
    </ul>
  </div>
  <% end %>
    </div>
</div>

app/views/expenses/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @expense, local: true) do |form| %>
      <%= form.text_field :ex_amount, placeholder: "1,000円" %>
      <%= form.text_field :about_ex, placeholder: "表参道のカフェ" %>
      <%= form.text_field :category_id %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="form-group">
  <div class="container">
    <h3>支出を記入</h3>
    <%= form_with(model: @expense, local: true, url:dashboard_expenses_path(Date.current.strftime('%Y-%m-%d'))) do |form| %>
        <div class='form-text-wrap'>
        <label class="form-text">金額</label>
        <span class="indispensable">必須</span>
        </div>
      <%= form.text_field :ex_amount, placeholder: "（例）1000", class:"price-input" %>
        
      <div class='form-text-wrap'>
        <label class="form-text">支出日</label>
        <span class="indispensable">必須</span>
       </div>
      <%= form.datetime_field :month %>

        <div class='form-text-wrap'>
        <label class="form-text">カテゴリー</label>
        <span class="indispensable">必須</span>
        </div>
      <%= form.collection_select(:category_id, Category.all, :id, :name,{}, {class:"select-box", id:"expense-category"}) %>

      <div class='form-text-wrap'>
        <label class="form-text">メモ</label>
        <span class="indispensable">必須</span>
        </div>
      <%= form.text_field :about_ex, placeholder: "（例）お店の名前など" %>

      <%= form.submit "記入する" %>
    <% end %>
  </div>
</div>

app/views/expenses/show.html.erb
  <div class="content_post" style="background-image: url(<%= @expense.image %>);">
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_expense_path(@expense.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', expense_path(@expense.id), method: :delete %>
        </li>
      </ul>
    </div>
    <p><%= @expense.text %></p>
    <span class="name"><%= @expense.name %>
    </span>
  </div>
</div>

app/views/incomes/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @expense, local: true) do |form| %>
      <%= form.text_field :ex_amount, placeholder: "1,000" %>
      <%= form.text_field :about_ex, placeholder: "ケーキセット" %>
      <%= form.text_field :category_id %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/incomes/new.html.erb
<div class="form-group">
  <div class="container">
    <h3>収入を記入</h3>
      <%= form_with(model: @income, local: true, url:dashboard_incomes_path(Date.current.strftime('%Y-%m-%d'))) do |form| %>
        <div class='form-text-wrap'>
          <label class="form-text">金額</label>
          <span class="indispensable">必須</span>
        </div>
        <%= form.text_field :in_amount, placeholder: "（例）1000",class:"price-input" %>
          <div class='form-text-wrap'>
            <label class="form-text">収入の種類</label>
            <span class="indispensable">必須</span>
          </div>
        <%= form.text_field :about_in, placeholder: "（例）給与" %>
          <div class='form-text-wrap'>
            <label class="form-text">収入日</label>
            <span class="indispensable">必須</span>
          </div>
        <%= form.datetime_field :month %>     
        <%= form.submit "記入する" %>
      <% end %>
  </div>
</div>

app/views/incomes/show.html.erb
  <div class="content_post" style="background-image: url(<%= @expense.image %>);">
    <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_expense_path(@expense.id), method: :get %>
        </li>
        <li>
          <%= link_to '削除', expense_path(@expenset.id), method: :delete %>
        </li>
      </ul>
    </div>
    <p><%= @expense.text %></p>
    <span class="name"><%= @expense.name %>
    </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>plus+minus-balance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.typekit.net/nfh8iwu.css">
  </head>
  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/"><%= image_tag "pmbalance.svg", :width => '180', class:"plus-minus-balance" %></a></h1>
        <% if user_signed_in? %>
          <div class="grid-6 strong">
            <div class="margin-r50">
              <%= link_to image_tag("in-pen.svg", :width => '85', class:"収入の記入"), new_dashboard_income_path(Date.current.strftime('%Y-%m-%d')) %>
              <%= link_to image_tag("ex-pen.svg", :width => '85', class:"支出の記入"), new_dashboard_expense_path(Date.current.strftime('%Y-%m-%d')) %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
            </div>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright plus+minus-balance 2020.
      </p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>